import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu/Menu";
import Image from "next/image";
import { styleText } from "util";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>My Application</title>
      </head>
      <body >
        <header className="header">
          <nav>
            <Menu />
          </nav>
        </header>
        <main className="container">

          {children}
          <div className="designlogo">
            <Image src={'../Images/designlogo.svg'} width={200} height={200} alt="designlogo" />
          </div>
        </main>
        <footer className="footer">

          <Footer />
        </footer>
      </body>
    </html>
  );
}
